name: Docs

on:
  push:
    branches:
      - master

jobs:
  trigger_remote_docs_build:
    runs-on: ubuntu-latest
    name: Trigger remote docs
    steps:
      - name: Trigger remote/local Github Action
        run: |
          curl -XPOST -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/cedadev/asset-scanner/actions/workflows/10252942/dispatches -d '{"ref":"master"}'